apiVersion: v1
kind: Service
metadata:
  name: my-test
  namespace: naruto
  labels:
    app: my-test
    team: naruto
    custom-label: my-awesome-app
spec:
  selector:
    app: my-test
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP